const icon = (name) => {
    const paths = {
        edge: '<path d="M5 5h14v14H5z"/><path d="m9 9 6 6m0-6-6 6"/>',
        overview: '<rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/>',
        nodes: '<path d="M5 12h14M12 5v14"/><circle cx="12" cy="5" r="2"/><circle cx="5" cy="12" r="2"/><circle cx="19" cy="12" r="2"/><circle cx="12" cy="19" r="2"/>',
        ip: '<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c3 3.4 3 14.6 0 18M12 3c-3 3.4-3 14.6 0 18"/>',
        settings: '<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.83 2.83-.06-.06A1.7 1.7 0 0 0 15 19.4a1.7 1.7 0 0 0-1 .6 1.7 1.7 0 0 0-.4 1.1V21H9.6v-.09A1.7 1.7 0 0 0 8.5 19.4a1.7 1.7 0 0 0-1.88.34l-.06.06-2.83-2.83.06-.06A1.7 1.7 0 0 0 4.6 15a1.7 1.7 0 0 0-.6-1 1.7 1.7 0 0 0-1.1-.4H3V9.6h.09A1.7 1.7 0 0 0 4.6 8.5a1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.83-2.83.06.06A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-.6 1.7 1.7 0 0 0 .4-1.1V3h4v.09A1.7 1.7 0 0 0 15.5 4.6a1.7 1.7 0 0 0 1.88-.34l.06-.06 2.83 2.83-.06.06A1.7 1.7 0 0 0 19.4 9c.37.28.6.7.6 1.16V13.6h-.09A1.7 1.7 0 0 0 19.4 15Z"/>',
        logs: '<path d="M4 5h16M4 12h16M4 19h16"/><circle cx="7" cy="5" r="1"/><circle cx="7" cy="12" r="1"/><circle cx="7" cy="19" r="1"/>',
        plug: '<path d="M9 12 4 7l3-3 5 5m3 3 5 5-3 3-5-5"/><path d="m14 10 4-4m-8 8-4 4"/>',
        shield: '<path d="M12 3 4 6v5c0 5 3.5 8.5 8 10 4.5-1.5 8-5 8-10V6l-8-3Z"/><path d="m9 12 2 2 4-5"/>',
        menu: '<path d="M4 6h16M4 12h16M4 18h16"/>',
        copy: '<rect x="8" y="8" width="11" height="11" rx="2"/><path d="M16 8V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h3"/>',
        download: '<path d="M12 3v12m0 0 4-4m-4 4-4-4"/><path d="M4 19h16"/>',
        qr: '<path d="M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM15 14h2v2h-2zM19 14h2v4h-2zM14 19h4v2h-4zM20 20h1v1h-1z"/>',
        refresh: '<path d="M20 6v5h-5M4 18v-5h5"/><path d="M18 9a7 7 0 0 0-12-2L4 11m16 2-2 4a7 7 0 0 1-12 0"/>',
    };
    return `<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">${paths[name] || paths.edge}</svg>`;
};

function escapeHtml(value) {
    return String(value || '').replace(/[&<>"']/g, (character) => ({
        '&': '&amp;',
        '<': '&lt;',
        '>': '&gt;',
        '"': '&quot;',
        "'": '&#39;',
    })[character]);
}

function head(title) {
    return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="light dark"><meta name="robots" content="noindex,nofollow,noarchive"><title>${escapeHtml(title)}</title><link rel="stylesheet" href="/assets/edgetunnel-ui.css"></head>`;
}

function brand() {
    return `<div class="brand"><span class="brand-mark">${icon('edge')}</span><span class="brand-copy"><strong>EdgeTunnel</strong><span>Control plane</span></span></div>`;
}

export function loginPage(error = '') {
    return `${head('EdgeTunnel 登录')}<body><main class="login-shell"><section class="login-card" aria-labelledby="login-title"><span class="login-glow"></span>${brand()}<h1 id="login-title">欢迎回来</h1><p>登录受保护的控制台，管理订阅、优选 IP 与运行状态。</p><form method="post"><div class="field"><label for="password">管理员密码</label><div class="password-wrap"><input id="password" name="password" type="password" autocomplete="current-password" required autofocus><button class="icon-button" type="button" data-toggle-password aria-label="显示密码">◉</button></div></div><p class="login-error${error ? '' : ' hidden'}" data-login-error>${escapeHtml(error)}</p><button class="button button-primary button-full" type="submit" data-login-button>进入控制台</button></form><div class="login-meta"><span class="status-dot"></span><span>凭据只发送到当前 Worker。会话存储在你的 KV 中，并使用安全的 HttpOnly Cookie。</span></div><noscript><p class="warning">建议启用 JavaScript 以获得完整控制台体验。</p></noscript></section></main><script defer src="/assets/edgetunnel-login.js"></script></body></html>`;
}

function navButton(view, label, iconName, active = false) {
    return `<button class="nav-button${active ? ' active' : ''}" type="button" data-view="${view}" data-view-label="${label}">${icon(iconName)}<span>${label}</span></button>`;
}

export function adminPage() {
    return `${head('EdgeTunnel 控制台')}<body><div class="loading-overlay" data-loading><div class="loader" aria-label="正在加载"></div></div><div class="toast-stack" aria-live="polite" data-toasts></div><div class="app-shell"><aside class="sidebar" data-sidebar>${brand()}<nav class="side-nav" aria-label="管理导航">${navButton('overview', '概览', 'overview', true)}${navButton('nodes', '节点与订阅', 'nodes')}${navButton('preferred', '优选 IP', 'ip')}${navButton('settings', '服务设置', 'settings')}${navButton('logs', '访问日志', 'logs')}${navButton('integrations', '集成与诊断', 'plug')}${navButton('security', '安全', 'shield')}</nav><div class="sidebar-footer"><div class="service-mini"><div class="status-line"><span class="status-dot"></span><span>Worker 可访问</span></div><p class="truncate" data-mini-host>正在读取域名…</p></div></div></aside><main class="main"><header class="topbar"><div class="topbar-copy"><p>Re_edgetunnel / 自托管控制台</p><h1 data-page-title>概览</h1></div><div class="topbar-actions"><button class="icon-button mobile-menu" type="button" data-menu aria-label="打开菜单">${icon('menu')}</button><button class="button button-ghost" type="button" data-refresh>${icon('refresh')}<span>刷新</span></button><a class="button" href="/logout">退出</a></div></header>

<section class="view active" data-view-panel="overview"><div class="section-head"><div><h2>服务概览</h2><p>展示配置状态与最近订阅活动，不改变数据转发路径。</p></div><span class="badge badge-success">管理平面在线</span></div><div class="grid metrics"><article class="card metric-card"><span class="metric-label">协议节点</span><div class="metric-value" data-metric-nodes>–</div><div class="metric-foot">VLESS · Trojan · Shadowsocks</div></article><article class="card metric-card"><span class="metric-label">传输层</span><div class="metric-value" data-metric-transports>–</div><div class="metric-foot">WS · XHTTP · gRPC</div></article><article class="card metric-card"><span class="metric-label">订阅请求</span><div class="metric-value" data-metric-requests>–</div><div class="metric-foot">来自当前 KV 日志</div></article><article class="card metric-card"><span class="metric-label">优选地址</span><div class="metric-value" data-metric-ips>–</div><div class="metric-foot">仅在导出 URL 中生效</div></article></div><div class="grid two-col" style="margin-top:16px"><article class="card"><div class="card-title"><div><h3>运行配置</h3><p>域名与隧道参数</p></div><span class="badge badge-blue" data-colo>CF EDGE</span></div><div class="detail-list"><div class="detail-row"><span>服务域名</span><strong class="mono truncate" data-service-host>–</strong><button class="icon-button" data-copy-field="host" aria-label="复制域名">${icon('copy')}</button></div><div class="detail-row"><span>隧道路径</span><strong class="mono truncate" data-service-path>–</strong><button class="icon-button" data-copy-field="path" aria-label="复制路径">${icon('copy')}</button></div><div class="detail-row"><span>凭据</span><strong class="mono truncate" data-service-uuid>–</strong><span class="badge">已遮挡</span></div><div class="detail-row"><span>客户端位置</span><strong class="truncate" data-client-location>–</strong><span></span></div></div><div class="card-title" style="margin-top:20px"><div><h3>协议矩阵</h3><p>配置可用，不代表本地线路延迟</p></div></div><div class="protocol-list" data-protocol-list></div></article><article class="card"><div class="card-title"><div><h3>快捷操作</h3><p>常用管理入口</p></div></div><div class="quick-actions"><button class="action-tile" data-go="nodes">${icon('download')}<strong>下载 Clash</strong><span>生成当前域名或优选 IP 配置</span></button><button class="action-tile" data-go="preferred">${icon('ip')}<strong>管理优选 IP</strong><span>导入本地扫描结果并生成 URL</span></button><button class="action-tile" data-copy-default-sub>${icon('copy')}<strong>复制订阅 URL</strong><span>保持现有服务配置不变</span></button><button class="action-tile" data-go="logs">${icon('logs')}<strong>查看访问日志</strong><span>Token 与敏感参数已脱敏</span></button></div><div class="warning" style="margin-top:16px">网页无法代替本地运营商线路扫描。这里负责保存结果和生成配置，真实优选仍应在你的设备上完成。</div></article></div></section>

<section class="view" data-view-panel="nodes"><div class="section-head"><div><h2>节点与订阅</h2><p>选择一个优选 IP，只替换节点的 server；SNI、Host、路径和凭据保持原样。</p></div><div class="section-actions"><a class="button" data-download-links href="#">${icon('download')}分享链接</a><a class="button button-primary" data-download-clash href="#">${icon('download')}Clash YAML</a></div></div><div class="endpoint-bar"><div class="field"><label for="preview-ip">优选 IP（可留空）</label><input id="preview-ip" class="input mono" placeholder="例如 104.18.35.249" data-preview-ip></div><div class="field"><label for="preview-port">端口</label><input id="preview-port" class="input" type="number" min="1" max="65535" value="443" data-preview-port></div><div class="field"><label for="preview-label">节点名称</label><input id="preview-label" class="input" placeholder="例如 CT-Guangzhou" data-preview-label></div><button class="button button-primary" type="button" data-build-preview>生成配置</button></div><div class="grid equal-col"><article class="card"><div class="card-title"><div><h3>可刷新订阅 URL</h3><p>URL 中的 ip 参数决定下载配置的 server</p></div></div><div class="export-grid"><div class="export-row"><label>Clash</label><code class="export-url" data-clash-url>–</code><button class="icon-button" data-copy-url="clash" aria-label="复制 Clash URL">${icon('copy')}</button></div><div class="export-row"><label>链接</label><code class="export-url" data-links-url>–</code><button class="icon-button" data-copy-url="links" aria-label="复制链接 URL">${icon('copy')}</button></div></div></article><article class="card"><div class="card-title"><div><h3>导出边界</h3><p>参数只作用于生成内容</p></div><span class="badge badge-success">内核零改动</span></div><div class="detail-list"><div class="detail-row"><span>替换</span><strong>server / port</strong><span class="badge">URL 参数</span></div><div class="detail-row"><span>保持</span><strong>SNI · Host · Path</strong><span class="badge">固定</span></div><div class="detail-row"><span>鉴权</span><strong>订阅 Token</strong><span class="badge">必需</span></div></div></article></div><div class="section-head" style="margin-top:24px"><div><h2>节点预览</h2><p data-preview-summary>正在生成节点…</p></div></div><div class="grid node-grid" data-node-grid></div></section>

<section class="view" data-view-panel="preferred"><div class="section-head"><div><h2>优选 IP 库</h2><p>保存你在本地扫描出的结果；选中后可直接跳转到节点生成器。</p></div><button class="button button-primary" type="button" data-use-selected>使用已选地址生成配置</button></div><div class="grid two-col"><article class="card"><div class="card-title"><div><h3>已保存地址</h3><p>数据存储在当前 Worker KV</p></div><span class="badge" data-ip-count>0 项</span></div><div class="ip-table" data-ip-table></div></article><article class="card"><div class="card-title"><div><h3>导入扫描结果</h3><p>每行一个 IP，可附端口、名称与延迟</p></div></div><form data-ip-import-form><div class="field"><label for="ip-import">支持格式</label><textarea id="ip-import" class="mono" data-ip-import placeholder="104.18.35.249:443#CT-Guangzhou,28ms&#10;[2606:4700::1111]:443#IPv6,42ms"></textarea><span class="hint">延迟仅作为你本地扫描的备注展示，控制台不会伪装成真实测速器。</span></div><div class="form-actions"><button class="button" type="button" data-clear-ip-import>清空</button><button class="button button-primary" type="submit">导入并保存</button></div></form></article></div></section>

<section class="view" data-view-panel="settings"><div class="section-head"><div><h2>服务设置</h2><p>只编辑订阅生成参数，不改变 Worker 的协议转发实现。</p></div><div class="section-actions"><span class="badge" data-settings-source>KV 配置</span><button class="button" type="button" data-export-backup>导出备份</button><button class="button" type="button" data-import-backup>导入备份</button><input class="hidden" type="file" accept="application/json,.json" data-backup-file></div></div><form class="card" data-settings-form><div class="form-grid"><div class="field"><label for="sub-name">订阅名称</label><input id="sub-name" name="subscriptionName" maxlength="64" required></div><div class="field"><label for="tunnel-path">隧道路径</label><input id="tunnel-path" name="tunnelPath" class="mono" maxlength="256" required></div><div class="field"><label for="fingerprint">TLS 指纹</label><select id="fingerprint" name="fingerprint"><option value="chrome">Chrome</option><option value="firefox">Firefox</option><option value="safari">Safari</option><option value="random">Random</option></select></div><div class="field"><label for="update-interval">订阅刷新间隔（小时）</label><input id="update-interval" name="updateInterval" type="number" min="1" max="168"></div><div class="field span-2"><span class="field-label">传输协议</span><div class="checks"><label class="check-card"><input type="checkbox" name="transport" value="ws"> WebSocket</label><label class="check-card"><input type="checkbox" name="transport" value="xhttp"> XHTTP</label><label class="check-card"><input type="checkbox" name="transport" value="grpc"> gRPC</label></div></div><div class="field span-2"><span class="field-label">可选行为</span><div class="checks"><label class="check-card"><input type="checkbox" name="shadowsocks"> Shadowsocks WS</label><label class="check-card"><input type="checkbox" name="zeroRtt"> WebSocket 0-RTT</label><label class="check-card"><input type="checkbox" name="skipCertificateVerification"> 跳过证书校验</label></div></div></div><div class="warning" style="margin-top:18px">如果通过 Wrangler 环境变量设置了 PATH，环境变量优先，控制台不会覆盖它。修改后现有订阅 URL 和 Token 不变。备份不会包含 ADMIN、UUID、Token 或第三方集成密钥。</div><div class="form-actions"><button class="button button-danger" type="button" data-reset-defaults>恢复默认配置</button><button class="button" type="button" data-reset-settings>恢复界面值</button><button class="button button-primary" type="submit">保存设置</button></div></form></section>

<section class="view" data-view-panel="logs"><div class="section-head"><div><h2>访问日志</h2><p>展示最近记录；订阅 Token、密码和 API Key 已从日志 URL 中移除。</p></div><button class="button button-danger" type="button" data-clear-logs>清空日志</button></div><article class="card"><div class="log-toolbar"><input class="input" type="search" placeholder="搜索 IP、路径、UA" data-log-search><select class="input" data-log-type><option value="">全部类型</option><option value="Get_SUB">订阅</option><option value="Proxy">代理</option></select><button class="button" type="button" data-refresh-logs>${icon('refresh')}刷新</button></div><div class="log-list" data-log-list></div></article></section>

<section class="view" data-view-panel="integrations"><div class="section-head"><div><h2>集成与诊断</h2><p>敏感值只通过同源 POST 提交，不进入 URL；读取时不会回显。</p></div></div><div class="grid equal-col"><form class="card integration-card" data-cf-form><div class="integration-status"><div><h3 style="margin:0">Cloudflare 用量</h3><p class="muted" style="margin:5px 0 0;font-size:12px">可选，不配置也不影响隧道</p></div><span class="badge" data-cf-status>未配置</span></div><div class="field"><label>认证方式</label><select name="mode"><option value="none">禁用</option><option value="token">Account ID + API Token</option><option value="global">Email + Global API Key</option><option value="usage">自有 Usage API</option></select></div><div class="field"><label>Account ID / Email / Usage API</label><input name="identity" autocomplete="off"></div><div class="field"><label>API Token / Global API Key</label><input name="secret" type="password" autocomplete="new-password"></div><button class="button button-primary" type="submit">保存 Cloudflare 集成</button></form><form class="card integration-card" data-tg-form><div class="integration-status"><div><h3 style="margin:0">Telegram 通知</h3><p class="muted" style="margin:5px 0 0;font-size:12px">订阅访问提醒</p></div><span class="badge" data-tg-status>未配置</span></div><div class="field"><label>Bot Token</label><input name="botToken" type="password" autocomplete="new-password"></div><div class="field"><label>Chat ID</label><input name="chatId" autocomplete="off"></div><label class="check-card"><input type="checkbox" name="enabled"> 启用通知</label><button class="button button-primary" type="submit">保存 Telegram 集成</button></form></div><article class="card" style="margin-top:16px"><div class="card-title"><div><h3>上游代理诊断</h3><p>仅在服务端配置了 PROXY_CHECK_HOST 时可用</p></div><span class="badge" data-proxy-check-status>按需测试</span></div><form class="form-grid" data-proxy-check-form><div class="field"><label>代理类型</label><select name="type"><option value="socks5">SOCKS5</option><option value="http">HTTP CONNECT</option></select></div><div class="field"><label>代理地址</label><input name="value" class="mono" placeholder="user:password@host:port" autocomplete="off" required></div><div class="span-2 form-actions"><button class="button" type="submit">开始诊断</button></div></form><pre class="link-box mono hidden" data-proxy-check-result></pre></article></section>

<section class="view" data-view-panel="security"><div class="section-head"><div><h2>安全</h2><p>管理会话与高风险操作。协议凭据不会在控制台明文展示。</p></div></div><div class="grid equal-col"><article class="card"><div class="card-title"><div><h3>当前会话</h3><p>24 小时服务端 KV 会话</p></div><span class="badge badge-success">已认证</span></div><div class="detail-list"><div class="detail-row"><span>Cookie</span><strong>HttpOnly · Secure</strong><span class="badge">Strict</span></div><div class="detail-row"><span>请求保护</span><strong>同源校验</strong><span class="badge">启用</span></div><div class="detail-row"><span>页面策略</span><strong>CSP · No frame</strong><span class="badge">启用</span></div></div></article><article class="card danger-zone"><div class="card-title"><div><h3>撤销所有会话</h3><p>删除 KV 中所有 session:* 条目</p></div></div><p class="muted" style="font-size:13px;line-height:1.6">操作后所有已登录浏览器都会退出，订阅 URL 与代理节点不受影响。</p><button class="button button-danger" type="button" data-revoke-sessions>撤销全部会话</button></article></div></section>

</main></div><dialog data-qr-dialog><div class="dialog-head"><h3>节点二维码</h3><button class="icon-button" type="button" data-close-qr aria-label="关闭">×</button></div><div class="dialog-body"><div class="qr-stage" data-qr-stage></div><p class="qr-caption" data-qr-caption></p></div></dialog><script defer src="/assets/edgetunnel-admin.js"></script></body></html>`;
}

export const UI_ICONS = { copy: icon('copy'), qr: icon('qr'), download: icon('download') };
